service: cyberjosef
image: sergey-yakushevich/cyberjosef

servers:
  web:
    - 213.134.31.142

proxy:
  ssl: true
  hosts:
    - cyberjosef.dev
    - www.cyberjosef.dev
  app_port: 80

registry:
  server: ghcr.io
  username: sergey-yakushevich
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - SECRET_KEY_BASE
  clear:
    SOLID_QUEUE_IN_PUMA: true
    WEB_CONCURRENCY: 1

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f

volumes:
  - "cyberjosef_storage:/rails/storage"

builder:
  arch: amd64

ssh:
  keys:
    - ~/.ssh/cyberjosef_deploy

asset_path: /rails/public/vite
